<?php

$mime_types = array
(
	'application/x-download',
	"application/msword",
	"application/octet-stream",
	"application/pdf",
	"application/postscript",
	"application/rtf",
	"application/vnd.ms-excel",
	"application/vnd.ms-outlook",
	"application/vnd.ms-powerpoint",
	"application/vnd.ms-project",
	"application/vnd.ms-works",
	"application/winhlp",
	"application/x-compres",
	"application/x-compressed",
	"application/x-cpio",
	"application/x-csh",
	"application/x-gtar",
	"application/x-gzip",
	"application/x-javascript",
	"application/x-msaccess",
	"application/x-msdownload",
	"application/x-msmoney",
	"application/x-mspublisher",
	"application/x-msschedule",
	"application/x-msterminal",
	"application/x-mswrite",
	"application/x-sh",
	"application/x-shar",
	"application/x-stuffit",
	"application/x-tar",
	"application/zip",
	"audio/basic",
	"audio/mid",
	"audio/mpeg",
	"audio/x-aiff",
	"audio/x-mpegurl",
	"audio/x-pn-realaudio",
	"audio/x-wav",
	"image/bmp",
	"image/gif",
	"image/jpeg",
	"image/png",
	"image/tiff",
	"image/x-icon",
	"text/css",
	"text/html",
	"text/plain",
	"text/richtext",
	"video/mpeg",
	"video/quicktime",
	"video/x-la-asf",
	"video/x-msvideo",
);

$extension_to_mime = array
(
	"jpg"  => "image/jpeg",
	"jpeg" => "image/jpeg",
	"png"  => "image/png",
	"zip"  => "application/zip",
	"gz"   => "application/x-gzip",
	"rar"  => "application/zip",
	"pdf"  => "application/pdf",
	"tar"  => "application/x-tar",
);
?>